### ISSUE TITLE
Github CI server feature

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#42]
- [x] Integrate with webhooks
- [x] Tutorial for creating a Github application
- [x] Integrate Github app certificates
- [x] Integrate with Github's [event_suite](https://developer.github.com/v3/activity/events/types/#checksuiteevent)
