### ISSUE TITLE
Implement teams

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#45]
As a user I should be able to:

- [x] See the list of groups I belong to
- [x] Create, edit and delete users I manage
- [x] Assign services & workflows to teams I belong to
- [x] Browser through services & workflows of teams I belong to.
- [x] Assign / unassign users to groups I can manage

As a group, my users can have 3 roles:

- [x] ADMIN: Can do anything with the group (change name / invite&kick members / delete the group / etc)
- [ ] ~MANAGER: Can invite and kick members.~
- [x] USER: Have no access to make any change on the group

As an admin I should be able to:

- [x] Create, edit and delete teams
- [ ] ~Assign / unassign users to any groups~
- [x] Allow / Disallow creation of groups for users

Other pending tasks:

- [x] lib.downloadFile to query files per authenticatedUserTeams, not per authenticatedUser
