### ISSUE TITLE
Change the flow's editor 

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#5]
The objective is to switch to a new UI for editing flows.

Right now the UI is pretty simple. You click on a button, and it adds an extra step to the flow, which will be executed after all previous tasks.

The new flows UI editor should be diagram-like based. So flow steps order can be changed, be executed in parallel, etc.

https://github.com/jsplumb/jsPlumb

- [x] Implement new flows editor UI
- [x] Adapt the queue (flows execution login) to the new data model
- [x] Check that non-next steps don't set the execution status to finished
- [x] If an step fails, stop all the execution
- [x] Click-to-edit steps
- [x] Test

**Comment by joseconstela** [comment]
#29

**Comment by joseconstela** [comment]
Current progress

![execution_diagram](https://user-images.githubusercontent.com/6388629/56231172-179fb880-607e-11e9-8eb8-d36156ec98a8.jpg)
