### ISSUE TITLE
Add files support

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#53]
Users can create files that can be used on processes.

- [x] Can be created by user
- [x] User file creation uses ace editor with md, js and text support
- [x] Can be edited by user
- [x] Can be removed by user
- [x] Can be downloaded only by authenticated users
- [x] Users can not see each others files
- [x] Editing files manually create a new version of the file, instead of replacing it.
- [x] Can be used as part of WebParsy configuration
- [x] Can be used as part of Agent configuration
- [x] Can be used as part of GithubCI configuration
- [x] Can be created as a process action (the content of the file will be the output of previous task(s)
- [x] When creating or editing files via ace editor, they are stored 'text'-like mimetype for default format files.
- [x] Can be used as the input of an action
- [x] File editor won't work for non edition-supported (I.e. only js, md, txt, json, files + those files created by the user via ace editor are actually editable). All other files (pdf, etc) are presented with a download link instead of showing the editor.
