### ISSUE TITLE
Add workflow templates & wizards

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#62]
As a user, I must be able to create a predefined workflow from a template provided by Tideflow's.

This templates are added to the database during install time (as for files templates)

- [ ] Create flow templates collection
- [ ] Create list of templates on UI
- [ ] When selecting a template in the UI, load the editor with the template's content 
- [ ] Add an script that will store file templates on the database when Tideflow is installed.
- [ ] Add useful file templates

**Comment by joseconstela** [comment]
Moving out of roadmap
